const START_LOADING = "START_LOADING";
const STOP_LOADING = "STOP_LOADING";
const FETCH_CART_DATA = "FETCH_CART_DATA";
const FETCH_USER_DATA = "FETCH_USER_DATA";
export { 
    START_LOADING, 
    STOP_LOADING, 
    FETCH_CART_DATA,
    FETCH_USER_DATA
 };
