//category =============================================================
GET http://localhost:5000/admin/category

###
GET http://localhost:5000/admin/get-one-category?id=2

###
POST http://localhost:5000/admin/category
content-type: application/json

{
    "data": {
        "name": "Giày"
    }
}

###
PUT  http://localhost:5000/admin/category?id=1
content-type: application/json

{
    "data": {
        "Name": "Test Category 1 update"
    }
}

###
DELETE   http://localhost:5000/admin/category?id=1

###
GET    http://localhost:5000/category


/// brand ===================================================================
###

POST http://localhost:5000/admin/brand
content-type: application/json

{
    "data": {
        "name": "Goya",
        "avatar": "",
        "category_id":"2"
    }
}

###

PUT  http://localhost:5000/admin/brand/2
content-type: application/json

{
    "data": {
        "Name": "Test Brand 2 update",
        "Avatar": "/img/imgUpload/1de9df6e63e5b4bbedf4.jpg",
        "CategoryId":"2"
    }
}

###

GET http://localhost:5000/admin/brand

###

GET http://localhost:5000/admin/one-brand/2

###

DELETE  http://localhost:5000/admin/brand/2


/// product ===================================================================
###

POST http://localhost:5000/admin/product
content-type: application/json

{
    "data": {
        "name": "iPhone 14 Pro Max",
        "img_preview": "/img/imgUpload/iphone-12-violet-1-600x600 (1).webp",
        "description":"Article 1",
        "brand_id": "1",
        "category_id": "1"
    }
}

### 
POST http://localhost:5000/admin/variation
content-type: application/json

{
    "data": {
        "name": "iPhone 14 Pro Max Đỏ 128GB",
        "SKU": "IP14PMDD128",
        "qty_in_stock":50,
        "import_price":17000000,
        "price":23000000,
        "sale_price":21000000,
        "product_id": "1"
    }
}


###
POST http://localhost:5000/admin/variation
content-type: application/json

{
    "data": {
        "name": "Giày Chạy Bộ Goya Training Plus 2023 Màu Vàng Đỏ Size 39",
        "SKU": "GCBGTP2023D39",
        "qty_in_stock":50,
        "import_price":350000,
        "price":750000,
        "sale_price":550000,
        "product_id": "2"
    }
}


###
POST http://localhost:5000/admin/product
content-type: application/json

{
    "data": {
        "name": "Giày Chạy Bộ Goya Training Plus 2023 ",
        "img_preview": "/img/imgUpload/Giày Chạy Bộ Goya Training Plus 2023.webp",
        "description":"Article 2",
        "brand_id": "3",
        "category_id": "2"
    }
}



###
POST http://localhost:5000/admin/option
content-type: application/json

{
    "data": {
        "name": "Size",
        "product_id": "2"
    }
}


###
GET http://localhost:5000/admin/option/1

###
GET http://localhost:5000/option/1

###
POST http://localhost:5000/admin/option-value
content-type: application/json

{
    "data": {
        "value": "#e70505",
        "option_id": "1"
    }
}


###
GET http://localhost:5000/admin/option-value/1



###
POST http://localhost:5000/admin/combination
content-type: application/json

{
    "data": {
        "option_value_id": "7",
        "variation_id": "6"
    }
}

/// attribute ===================================================================
###

POST http://localhost:5000/admin/attribute
content-type: application/json

{
    "data": {
        "name": "Dung lượng lưu trữ",
        "category_id": "1"
    }
}

###

GET  http://localhost:5000/admin/attribute

###
GET  http://localhost:5000/admin/get-attribute-by-category/1



###
GET  http://localhost:5000/admin/get-variation-by-product/4

/// attribute ===================================================================
###

POST http://localhost:5000/admin/product
content-type: application/json

{
    "data": {
        "Name": "iPhone 15",
        "CategoryId": "7",
        "BrandId": "9",
        "Version": "128GB",
        "Article": "Jabra Evolve2 75 USB-A MS Teams Stereo Headset The Jabra Evolve2 75 USB-A MS Teams Stereo Headset has replaced previous hybrid working standards. Industry-leading call quality thanks to top-notch audio engineering. With this intelligent headset, you can stay connected and productive from the first call of the day to the last train home. With an ergonomic earcup design, this headset invented a brand-new dual-foam technology."
    }
}

###
GET http://localhost:5000/admin/product

###
GET http://localhost:5000/admin/product/1

###
GET http://localhost:5000/product-detail/1?arrayParam=64GB,đỏ


/// color ===================================================================
###

POST http://localhost:5000/admin/color
content-type: application/json

{
    "data": {
        "Name": "Đen",
        "CategoryId": "7",
        "Color": "test",
        "ImportPrice": "200",
        "Price": "250",
        "DiscountPrice": "235",
        "Avatar": "Avatar",
        "NumberOfRate": "49",
        "AverageRate": "5",
        "Sold": "235",
        "ProductId": 2

    }
}



/// color ===================================================================
###

POST http://localhost:5000/admin/attribute-value
content-type: application/json

{
    "data": 
        [
            {
                "variation_id": 1,
                "attribute_id": 1,
                "value": "OLED"
            },
            {
                "variation_id": 1,
                "attribute_id": 2,
                "value": "4 GB"
            },
            {
                "variation_id": 1,
                "attribute_id": 5,
                "value": "12 MP"
            },
            {
                "variation_id": 1,
                "attribute_id": 6,
                "value": "Hỗ trợ 5G"
            },
            {
                "variation_id": 1,
                "attribute_id": 7,
                "value": " 2815 mAh"
            },
            {
                "variation_id": 1,
                "attribute_id": 8,
                "value": " 20 W"
            }
        ]

    
}



/// list - img ===================================================================
###

POST http://localhost:5000/admin/list-img
content-type: application/json

{
    "data": 
        [
            {
                "variation_id": 1,
                "url": "/img/imgUpload/logo_xiaomi.png"
            },
            {
                "variation_id": 1,
                "url": "/img/imgUpload/logo_xiaomi1.png"
            },
            {
                "variation_id": 1,
                "url": "/img/imgUpload/logo_xiaomi2.png"
            }
        ]

    
}


###
GET  http://localhost:5000/admin/get-list-img/1

###
GET  http://localhost:5000/admin/get-variation-by-product/1